### ISSUE TITLE
Create docs for deploying umbrella repositories

### ISSUE THREAD

**Issue by benlk** [INN/docs#154]
This should cover at a minimum:

- [ ] links to deploy-tools installation stuff
- [ ] updating child theme, commit, push
- [ ] update umbrella with new submodule, commit, push
- [ ] `workon largo`
- [ ] `fab staging branch:staging dry_run deploy`
- [ ] `fab staging branch:staging deploy`

@aschweigert, @rclations, what else do you think this needs?

Where should the file be placed in these docs?

**Comment by benlk** [comment]
Old issue: #99

**Comment by benlk** [comment]
Mostly covered at https://github.com/INN/deploy-tools/blob/master/docs/deploy.md
