### ISSUE TITLE
checklist for creation of new projects

### ISSUE THREAD

**Issue by aschweigert** [INN/docs#77]
I'm thinking things like:

- [ ] how to setup and structure new git repos (adding readme.md and contributing.md and how they should be structured, process for adding docs, creating default github issue set (#63), etc.
- [ ] creation of project description in the projects folder in this repo, how to structure the project readme and manifesto we include here
- [ ] where we keep projects assets, contracts, etc. if it's a client project that we wouldn't add here
